#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneKayit.V1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hastane")]
	public partial class HastaneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_FaturaBilgileri(tbl_FaturaBilgileri instance);
    partial void Updatetbl_FaturaBilgileri(tbl_FaturaBilgileri instance);
    partial void Deletetbl_FaturaBilgileri(tbl_FaturaBilgileri instance);
    partial void Inserttbl_HastaGecmisi(tbl_HastaGecmisi instance);
    partial void Updatetbl_HastaGecmisi(tbl_HastaGecmisi instance);
    partial void Deletetbl_HastaGecmisi(tbl_HastaGecmisi instance);
    partial void Inserttbl_Ilac(tbl_Ilac instance);
    partial void Updatetbl_Ilac(tbl_Ilac instance);
    partial void Deletetbl_Ilac(tbl_Ilac instance);
    partial void Inserttbl_OdaDrumu(tbl_OdaDrumu instance);
    partial void Updatetbl_OdaDrumu(tbl_OdaDrumu instance);
    partial void Deletetbl_OdaDrumu(tbl_OdaDrumu instance);
    partial void Inserttbl_Personel(tbl_Personel instance);
    partial void Updatetbl_Personel(tbl_Personel instance);
    partial void Deletetbl_Personel(tbl_Personel instance);
    partial void Inserttbl_Randevular(tbl_Randevular instance);
    partial void Updatetbl_Randevular(tbl_Randevular instance);
    partial void Deletetbl_Randevular(tbl_Randevular instance);
    partial void Inserttbl_Receteler(tbl_Receteler instance);
    partial void Updatetbl_Receteler(tbl_Receteler instance);
    partial void Deletetbl_Receteler(tbl_Receteler instance);
    partial void Inserttbl_Bolum(tbl_Bolum instance);
    partial void Updatetbl_Bolum(tbl_Bolum instance);
    partial void Deletetbl_Bolum(tbl_Bolum instance);
    partial void Inserttbl_MuayeneBilgileri(tbl_MuayeneBilgileri instance);
    partial void Updatetbl_MuayeneBilgileri(tbl_MuayeneBilgileri instance);
    partial void Deletetbl_MuayeneBilgileri(tbl_MuayeneBilgileri instance);
    partial void Inserttbl_Hastalar(tbl_Hastalar instance);
    partial void Updatetbl_Hastalar(tbl_Hastalar instance);
    partial void Deletetbl_Hastalar(tbl_Hastalar instance);
    partial void Inserttbl_Doktorlar(tbl_Doktorlar instance);
    partial void Updatetbl_Doktorlar(tbl_Doktorlar instance);
    partial void Deletetbl_Doktorlar(tbl_Doktorlar instance);
    partial void Inserttbl_Yonetici(tbl_Yonetici instance);
    partial void Updatetbl_Yonetici(tbl_Yonetici instance);
    partial void Deletetbl_Yonetici(tbl_Yonetici instance);
    partial void Inserttbl_Duyuru(tbl_Duyuru instance);
    partial void Updatetbl_Duyuru(tbl_Duyuru instance);
    partial void Deletetbl_Duyuru(tbl_Duyuru instance);
    #endregion
		
		public HastaneDataContext() : 
				base(global::HastaneKayit.V1.Properties.Settings.Default.HastaneConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HastaneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HastaneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HastaneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HastaneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_FaturaBilgileri> tbl_FaturaBilgileris
		{
			get
			{
				return this.GetTable<tbl_FaturaBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<tbl_HastaGecmisi> tbl_HastaGecmisis
		{
			get
			{
				return this.GetTable<tbl_HastaGecmisi>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Ilac> tbl_Ilacs
		{
			get
			{
				return this.GetTable<tbl_Ilac>();
			}
		}
		
		public System.Data.Linq.Table<tbl_OdaDrumu> tbl_OdaDrumus
		{
			get
			{
				return this.GetTable<tbl_OdaDrumu>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Personel> tbl_Personels
		{
			get
			{
				return this.GetTable<tbl_Personel>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Randevular> tbl_Randevulars
		{
			get
			{
				return this.GetTable<tbl_Randevular>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Receteler> tbl_Recetelers
		{
			get
			{
				return this.GetTable<tbl_Receteler>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Bolum> tbl_Bolums
		{
			get
			{
				return this.GetTable<tbl_Bolum>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MuayeneBilgileri> tbl_MuayeneBilgileris
		{
			get
			{
				return this.GetTable<tbl_MuayeneBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Hastalar> tbl_Hastalars
		{
			get
			{
				return this.GetTable<tbl_Hastalar>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Doktorlar> tbl_Doktorlars
		{
			get
			{
				return this.GetTable<tbl_Doktorlar>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Yonetici> tbl_Yoneticis
		{
			get
			{
				return this.GetTable<tbl_Yonetici>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Duyuru> tbl_Duyurus
		{
			get
			{
				return this.GetTable<tbl_Duyuru>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_FaturaBilgileri")]
	public partial class tbl_FaturaBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FaturaID;
		
		private System.Nullable<int> _HastaID;
		
		private System.Nullable<System.DateTime> _FaturaTarihi;
		
		private System.Nullable<decimal> _OdemeMiktari;
		
		private EntityRef<tbl_Hastalar> _tbl_Hastalar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFaturaIDChanging(int value);
    partial void OnFaturaIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnFaturaTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnFaturaTarihiChanged();
    partial void OnOdemeMiktariChanging(System.Nullable<decimal> value);
    partial void OnOdemeMiktariChanged();
    #endregion
		
		public tbl_FaturaBilgileri()
		{
			this._tbl_Hastalar = default(EntityRef<tbl_Hastalar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaturaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FaturaID
		{
			get
			{
				return this._FaturaID;
			}
			set
			{
				if ((this._FaturaID != value))
				{
					this.OnFaturaIDChanging(value);
					this.SendPropertyChanging();
					this._FaturaID = value;
					this.SendPropertyChanged("FaturaID");
					this.OnFaturaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tbl_Hastalar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaturaTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> FaturaTarihi
		{
			get
			{
				return this._FaturaTarihi;
			}
			set
			{
				if ((this._FaturaTarihi != value))
				{
					this.OnFaturaTarihiChanging(value);
					this.SendPropertyChanging();
					this._FaturaTarihi = value;
					this.SendPropertyChanged("FaturaTarihi");
					this.OnFaturaTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeMiktari", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> OdemeMiktari
		{
			get
			{
				return this._OdemeMiktari;
			}
			set
			{
				if ((this._OdemeMiktari != value))
				{
					this.OnOdemeMiktariChanging(value);
					this.SendPropertyChanging();
					this._OdemeMiktari = value;
					this.SendPropertyChanged("OdemeMiktari");
					this.OnOdemeMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_FaturaBilgileri", Storage="_tbl_Hastalar", ThisKey="HastaID", OtherKey="HastaID", IsForeignKey=true)]
		public tbl_Hastalar tbl_Hastalar
		{
			get
			{
				return this._tbl_Hastalar.Entity;
			}
			set
			{
				tbl_Hastalar previousValue = this._tbl_Hastalar.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hastalar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hastalar.Entity = null;
						previousValue.tbl_FaturaBilgileris.Remove(this);
					}
					this._tbl_Hastalar.Entity = value;
					if ((value != null))
					{
						value.tbl_FaturaBilgileris.Add(this);
						this._HastaID = value.HastaID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hastalar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HastaGecmisi")]
	public partial class tbl_HastaGecmisi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GecmisID;
		
		private System.Nullable<int> _HastaID;
		
		private string _Tedavi;
		
		private EntityRef<tbl_Hastalar> _tbl_Hastalar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGecmisIDChanging(int value);
    partial void OnGecmisIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnTedaviChanging(string value);
    partial void OnTedaviChanged();
    #endregion
		
		public tbl_HastaGecmisi()
		{
			this._tbl_Hastalar = default(EntityRef<tbl_Hastalar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GecmisID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GecmisID
		{
			get
			{
				return this._GecmisID;
			}
			set
			{
				if ((this._GecmisID != value))
				{
					this.OnGecmisIDChanging(value);
					this.SendPropertyChanging();
					this._GecmisID = value;
					this.SendPropertyChanged("GecmisID");
					this.OnGecmisIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tbl_Hastalar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tedavi", DbType="VarChar(255)")]
		public string Tedavi
		{
			get
			{
				return this._Tedavi;
			}
			set
			{
				if ((this._Tedavi != value))
				{
					this.OnTedaviChanging(value);
					this.SendPropertyChanging();
					this._Tedavi = value;
					this.SendPropertyChanged("Tedavi");
					this.OnTedaviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_HastaGecmisi", Storage="_tbl_Hastalar", ThisKey="HastaID", OtherKey="HastaID", IsForeignKey=true)]
		public tbl_Hastalar tbl_Hastalar
		{
			get
			{
				return this._tbl_Hastalar.Entity;
			}
			set
			{
				tbl_Hastalar previousValue = this._tbl_Hastalar.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hastalar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hastalar.Entity = null;
						previousValue.tbl_HastaGecmisis.Remove(this);
					}
					this._tbl_Hastalar.Entity = value;
					if ((value != null))
					{
						value.tbl_HastaGecmisis.Add(this);
						this._HastaID = value.HastaID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hastalar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Ilac")]
	public partial class tbl_Ilac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IlacID;
		
		private string _IlacAdi;
		
		private System.Nullable<int> _StokMiktari;
		
		private System.Nullable<decimal> _Fiyat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIlacIDChanging(int value);
    partial void OnIlacIDChanged();
    partial void OnIlacAdiChanging(string value);
    partial void OnIlacAdiChanged();
    partial void OnStokMiktariChanging(System.Nullable<int> value);
    partial void OnStokMiktariChanged();
    partial void OnFiyatChanging(System.Nullable<decimal> value);
    partial void OnFiyatChanged();
    #endregion
		
		public tbl_Ilac()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IlacID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IlacID
		{
			get
			{
				return this._IlacID;
			}
			set
			{
				if ((this._IlacID != value))
				{
					this.OnIlacIDChanging(value);
					this.SendPropertyChanging();
					this._IlacID = value;
					this.SendPropertyChanged("IlacID");
					this.OnIlacIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IlacAdi", DbType="VarChar(100)")]
		public string IlacAdi
		{
			get
			{
				return this._IlacAdi;
			}
			set
			{
				if ((this._IlacAdi != value))
				{
					this.OnIlacAdiChanging(value);
					this.SendPropertyChanging();
					this._IlacAdi = value;
					this.SendPropertyChanged("IlacAdi");
					this.OnIlacAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokMiktari", DbType="Int")]
		public System.Nullable<int> StokMiktari
		{
			get
			{
				return this._StokMiktari;
			}
			set
			{
				if ((this._StokMiktari != value))
				{
					this.OnStokMiktariChanging(value);
					this.SendPropertyChanging();
					this._StokMiktari = value;
					this.SendPropertyChanged("StokMiktari");
					this.OnStokMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_OdaDrumu")]
	public partial class tbl_OdaDrumu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OdaID;
		
		private System.Nullable<int> _OdaNumarasi;
		
		private System.Nullable<byte> _DoluMu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOdaIDChanging(int value);
    partial void OnOdaIDChanged();
    partial void OnOdaNumarasiChanging(System.Nullable<int> value);
    partial void OnOdaNumarasiChanged();
    partial void OnDoluMuChanging(System.Nullable<byte> value);
    partial void OnDoluMuChanged();
    #endregion
		
		public tbl_OdaDrumu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OdaID
		{
			get
			{
				return this._OdaID;
			}
			set
			{
				if ((this._OdaID != value))
				{
					this.OnOdaIDChanging(value);
					this.SendPropertyChanging();
					this._OdaID = value;
					this.SendPropertyChanged("OdaID");
					this.OnOdaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdaNumarasi", DbType="Int")]
		public System.Nullable<int> OdaNumarasi
		{
			get
			{
				return this._OdaNumarasi;
			}
			set
			{
				if ((this._OdaNumarasi != value))
				{
					this.OnOdaNumarasiChanging(value);
					this.SendPropertyChanging();
					this._OdaNumarasi = value;
					this.SendPropertyChanged("OdaNumarasi");
					this.OnOdaNumarasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoluMu", DbType="TinyInt")]
		public System.Nullable<byte> DoluMu
		{
			get
			{
				return this._DoluMu;
			}
			set
			{
				if ((this._DoluMu != value))
				{
					this.OnDoluMuChanging(value);
					this.SendPropertyChanging();
					this._DoluMu = value;
					this.SendPropertyChanged("DoluMu");
					this.OnDoluMuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Personel")]
	public partial class tbl_Personel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonelID;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Departman;
		
		private string _Telefon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonelIDChanging(int value);
    partial void OnPersonelIDChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnDepartmanChanging(string value);
    partial void OnDepartmanChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    #endregion
		
		public tbl_Personel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="VarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="VarChar(50)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departman", DbType="VarChar(100)")]
		public string Departman
		{
			get
			{
				return this._Departman;
			}
			set
			{
				if ((this._Departman != value))
				{
					this.OnDepartmanChanging(value);
					this.SendPropertyChanging();
					this._Departman = value;
					this.SendPropertyChanged("Departman");
					this.OnDepartmanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(15)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Randevular")]
	public partial class tbl_Randevular : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RandevuID;
		
		private System.Nullable<System.DateTime> _RandevuTarihi;
		
		private System.Nullable<System.TimeSpan> _RandevuSaati;
		
		private System.Nullable<int> _DoktorID;
		
		private System.Nullable<int> _HastaID;
		
		private EntitySet<tbl_MuayeneBilgileri> _tbl_MuayeneBilgileris;
		
		private EntityRef<tbl_Hastalar> _tbl_Hastalar;
		
		private EntityRef<tbl_Doktorlar> _tbl_Doktorlar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRandevuIDChanging(int value);
    partial void OnRandevuIDChanged();
    partial void OnRandevuTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnRandevuTarihiChanged();
    partial void OnRandevuSaatiChanging(System.Nullable<System.TimeSpan> value);
    partial void OnRandevuSaatiChanged();
    partial void OnDoktorIDChanging(System.Nullable<int> value);
    partial void OnDoktorIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    #endregion
		
		public tbl_Randevular()
		{
			this._tbl_MuayeneBilgileris = new EntitySet<tbl_MuayeneBilgileri>(new Action<tbl_MuayeneBilgileri>(this.attach_tbl_MuayeneBilgileris), new Action<tbl_MuayeneBilgileri>(this.detach_tbl_MuayeneBilgileris));
			this._tbl_Hastalar = default(EntityRef<tbl_Hastalar>);
			this._tbl_Doktorlar = default(EntityRef<tbl_Doktorlar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RandevuID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RandevuID
		{
			get
			{
				return this._RandevuID;
			}
			set
			{
				if ((this._RandevuID != value))
				{
					this.OnRandevuIDChanging(value);
					this.SendPropertyChanging();
					this._RandevuID = value;
					this.SendPropertyChanged("RandevuID");
					this.OnRandevuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RandevuTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> RandevuTarihi
		{
			get
			{
				return this._RandevuTarihi;
			}
			set
			{
				if ((this._RandevuTarihi != value))
				{
					this.OnRandevuTarihiChanging(value);
					this.SendPropertyChanging();
					this._RandevuTarihi = value;
					this.SendPropertyChanged("RandevuTarihi");
					this.OnRandevuTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RandevuSaati", DbType="Time")]
		public System.Nullable<System.TimeSpan> RandevuSaati
		{
			get
			{
				return this._RandevuSaati;
			}
			set
			{
				if ((this._RandevuSaati != value))
				{
					this.OnRandevuSaatiChanging(value);
					this.SendPropertyChanging();
					this._RandevuSaati = value;
					this.SendPropertyChanged("RandevuSaati");
					this.OnRandevuSaatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorID", DbType="Int")]
		public System.Nullable<int> DoktorID
		{
			get
			{
				return this._DoktorID;
			}
			set
			{
				if ((this._DoktorID != value))
				{
					if (this._tbl_Doktorlar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDoktorIDChanging(value);
					this.SendPropertyChanging();
					this._DoktorID = value;
					this.SendPropertyChanged("DoktorID");
					this.OnDoktorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tbl_Hastalar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Randevular_tbl_MuayeneBilgileri", Storage="_tbl_MuayeneBilgileris", ThisKey="RandevuID", OtherKey="RandevuID")]
		public EntitySet<tbl_MuayeneBilgileri> tbl_MuayeneBilgileris
		{
			get
			{
				return this._tbl_MuayeneBilgileris;
			}
			set
			{
				this._tbl_MuayeneBilgileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_Randevular", Storage="_tbl_Hastalar", ThisKey="HastaID", OtherKey="HastaID", IsForeignKey=true)]
		public tbl_Hastalar tbl_Hastalar
		{
			get
			{
				return this._tbl_Hastalar.Entity;
			}
			set
			{
				tbl_Hastalar previousValue = this._tbl_Hastalar.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hastalar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hastalar.Entity = null;
						previousValue.tbl_Randevulars.Remove(this);
					}
					this._tbl_Hastalar.Entity = value;
					if ((value != null))
					{
						value.tbl_Randevulars.Add(this);
						this._HastaID = value.HastaID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hastalar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Doktorlar_tbl_Randevular", Storage="_tbl_Doktorlar", ThisKey="DoktorID", OtherKey="DoktorID", IsForeignKey=true)]
		public tbl_Doktorlar tbl_Doktorlar
		{
			get
			{
				return this._tbl_Doktorlar.Entity;
			}
			set
			{
				tbl_Doktorlar previousValue = this._tbl_Doktorlar.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Doktorlar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Doktorlar.Entity = null;
						previousValue.tbl_Randevulars.Remove(this);
					}
					this._tbl_Doktorlar.Entity = value;
					if ((value != null))
					{
						value.tbl_Randevulars.Add(this);
						this._DoktorID = value.DoktorID;
					}
					else
					{
						this._DoktorID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Doktorlar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_MuayeneBilgileris(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Randevular = this;
		}
		
		private void detach_tbl_MuayeneBilgileris(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Randevular = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Receteler")]
	public partial class tbl_Receteler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ReceteID;
		
		private System.Nullable<int> _MuayeneID;
		
		private string _IlacAdi;
		
		private string _Dozaj;
		
		private EntityRef<tbl_MuayeneBilgileri> _tbl_MuayeneBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReceteIDChanging(int value);
    partial void OnReceteIDChanged();
    partial void OnMuayeneIDChanging(System.Nullable<int> value);
    partial void OnMuayeneIDChanged();
    partial void OnIlacAdiChanging(string value);
    partial void OnIlacAdiChanged();
    partial void OnDozajChanging(string value);
    partial void OnDozajChanged();
    #endregion
		
		public tbl_Receteler()
		{
			this._tbl_MuayeneBilgileri = default(EntityRef<tbl_MuayeneBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceteID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ReceteID
		{
			get
			{
				return this._ReceteID;
			}
			set
			{
				if ((this._ReceteID != value))
				{
					this.OnReceteIDChanging(value);
					this.SendPropertyChanging();
					this._ReceteID = value;
					this.SendPropertyChanged("ReceteID");
					this.OnReceteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MuayeneID", DbType="Int")]
		public System.Nullable<int> MuayeneID
		{
			get
			{
				return this._MuayeneID;
			}
			set
			{
				if ((this._MuayeneID != value))
				{
					if (this._tbl_MuayeneBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMuayeneIDChanging(value);
					this.SendPropertyChanging();
					this._MuayeneID = value;
					this.SendPropertyChanged("MuayeneID");
					this.OnMuayeneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IlacAdi", DbType="VarChar(100)")]
		public string IlacAdi
		{
			get
			{
				return this._IlacAdi;
			}
			set
			{
				if ((this._IlacAdi != value))
				{
					this.OnIlacAdiChanging(value);
					this.SendPropertyChanging();
					this._IlacAdi = value;
					this.SendPropertyChanged("IlacAdi");
					this.OnIlacAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dozaj", DbType="VarChar(50)")]
		public string Dozaj
		{
			get
			{
				return this._Dozaj;
			}
			set
			{
				if ((this._Dozaj != value))
				{
					this.OnDozajChanging(value);
					this.SendPropertyChanging();
					this._Dozaj = value;
					this.SendPropertyChanged("Dozaj");
					this.OnDozajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_MuayeneBilgileri_tbl_Receteler", Storage="_tbl_MuayeneBilgileri", ThisKey="MuayeneID", OtherKey="MuayeneID", IsForeignKey=true)]
		public tbl_MuayeneBilgileri tbl_MuayeneBilgileri
		{
			get
			{
				return this._tbl_MuayeneBilgileri.Entity;
			}
			set
			{
				tbl_MuayeneBilgileri previousValue = this._tbl_MuayeneBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tbl_MuayeneBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_MuayeneBilgileri.Entity = null;
						previousValue.tbl_Recetelers.Remove(this);
					}
					this._tbl_MuayeneBilgileri.Entity = value;
					if ((value != null))
					{
						value.tbl_Recetelers.Add(this);
						this._MuayeneID = value.MuayeneID;
					}
					else
					{
						this._MuayeneID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_MuayeneBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Bolum")]
	public partial class tbl_Bolum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BolumID;
		
		private string _BolumAdi;
		
		private EntitySet<tbl_Doktorlar> _tbl_Doktorlars;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBolumIDChanging(int value);
    partial void OnBolumIDChanged();
    partial void OnBolumAdiChanging(string value);
    partial void OnBolumAdiChanged();
    #endregion
		
		public tbl_Bolum()
		{
			this._tbl_Doktorlars = new EntitySet<tbl_Doktorlar>(new Action<tbl_Doktorlar>(this.attach_tbl_Doktorlars), new Action<tbl_Doktorlar>(this.detach_tbl_Doktorlars));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BolumID
		{
			get
			{
				return this._BolumID;
			}
			set
			{
				if ((this._BolumID != value))
				{
					this.OnBolumIDChanging(value);
					this.SendPropertyChanging();
					this._BolumID = value;
					this.SendPropertyChanged("BolumID");
					this.OnBolumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumAdi", DbType="NVarChar(100)")]
		public string BolumAdi
		{
			get
			{
				return this._BolumAdi;
			}
			set
			{
				if ((this._BolumAdi != value))
				{
					this.OnBolumAdiChanging(value);
					this.SendPropertyChanging();
					this._BolumAdi = value;
					this.SendPropertyChanged("BolumAdi");
					this.OnBolumAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Bolum_tbl_Doktorlar", Storage="_tbl_Doktorlars", ThisKey="BolumID", OtherKey="BolumID")]
		public EntitySet<tbl_Doktorlar> tbl_Doktorlars
		{
			get
			{
				return this._tbl_Doktorlars;
			}
			set
			{
				this._tbl_Doktorlars.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Doktorlars(tbl_Doktorlar entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Bolum = this;
		}
		
		private void detach_tbl_Doktorlars(tbl_Doktorlar entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Bolum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MuayeneBilgileri")]
	public partial class tbl_MuayeneBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MuayeneID;
		
		private System.Nullable<int> _RandevuID;
		
		private System.Nullable<System.DateTime> _MuayeneTarihi;
		
		private string _Teşhis;
		
		private System.Nullable<int> _HastaID;
		
		private EntitySet<tbl_Receteler> _tbl_Recetelers;
		
		private EntityRef<tbl_Randevular> _tbl_Randevular;
		
		private EntityRef<tbl_Hastalar> _tbl_Hastalar;
		
		private EntityRef<tbl_Hastalar> _tbl_Hastalar1;
		
		private EntityRef<tbl_Hastalar> _tbl_Hastalar2;
		
		private EntityRef<tbl_Hastalar> _tbl_Hastalar3;
		
		private EntityRef<tbl_Hastalar> _tbl_Hastalar4;
		
		private EntityRef<tbl_Hastalar> _tbl_Hastalar5;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMuayeneIDChanging(int value);
    partial void OnMuayeneIDChanged();
    partial void OnRandevuIDChanging(System.Nullable<int> value);
    partial void OnRandevuIDChanged();
    partial void OnMuayeneTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnMuayeneTarihiChanged();
    partial void OnTeşhisChanging(string value);
    partial void OnTeşhisChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    #endregion
		
		public tbl_MuayeneBilgileri()
		{
			this._tbl_Recetelers = new EntitySet<tbl_Receteler>(new Action<tbl_Receteler>(this.attach_tbl_Recetelers), new Action<tbl_Receteler>(this.detach_tbl_Recetelers));
			this._tbl_Randevular = default(EntityRef<tbl_Randevular>);
			this._tbl_Hastalar = default(EntityRef<tbl_Hastalar>);
			this._tbl_Hastalar1 = default(EntityRef<tbl_Hastalar>);
			this._tbl_Hastalar2 = default(EntityRef<tbl_Hastalar>);
			this._tbl_Hastalar3 = default(EntityRef<tbl_Hastalar>);
			this._tbl_Hastalar4 = default(EntityRef<tbl_Hastalar>);
			this._tbl_Hastalar5 = default(EntityRef<tbl_Hastalar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MuayeneID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MuayeneID
		{
			get
			{
				return this._MuayeneID;
			}
			set
			{
				if ((this._MuayeneID != value))
				{
					this.OnMuayeneIDChanging(value);
					this.SendPropertyChanging();
					this._MuayeneID = value;
					this.SendPropertyChanged("MuayeneID");
					this.OnMuayeneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RandevuID", DbType="Int")]
		public System.Nullable<int> RandevuID
		{
			get
			{
				return this._RandevuID;
			}
			set
			{
				if ((this._RandevuID != value))
				{
					if (this._tbl_Randevular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRandevuIDChanging(value);
					this.SendPropertyChanging();
					this._RandevuID = value;
					this.SendPropertyChanged("RandevuID");
					this.OnRandevuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MuayeneTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> MuayeneTarihi
		{
			get
			{
				return this._MuayeneTarihi;
			}
			set
			{
				if ((this._MuayeneTarihi != value))
				{
					this.OnMuayeneTarihiChanging(value);
					this.SendPropertyChanging();
					this._MuayeneTarihi = value;
					this.SendPropertyChanged("MuayeneTarihi");
					this.OnMuayeneTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teşhis", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Teşhis
		{
			get
			{
				return this._Teşhis;
			}
			set
			{
				if ((this._Teşhis != value))
				{
					this.OnTeşhisChanging(value);
					this.SendPropertyChanging();
					this._Teşhis = value;
					this.SendPropertyChanged("Teşhis");
					this.OnTeşhisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if ((((((this._tbl_Hastalar.HasLoadedOrAssignedValue || this._tbl_Hastalar1.HasLoadedOrAssignedValue) 
								|| this._tbl_Hastalar2.HasLoadedOrAssignedValue) 
								|| this._tbl_Hastalar3.HasLoadedOrAssignedValue) 
								|| this._tbl_Hastalar4.HasLoadedOrAssignedValue) 
								|| this._tbl_Hastalar5.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_MuayeneBilgileri_tbl_Receteler", Storage="_tbl_Recetelers", ThisKey="MuayeneID", OtherKey="MuayeneID")]
		public EntitySet<tbl_Receteler> tbl_Recetelers
		{
			get
			{
				return this._tbl_Recetelers;
			}
			set
			{
				this._tbl_Recetelers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Randevular_tbl_MuayeneBilgileri", Storage="_tbl_Randevular", ThisKey="RandevuID", OtherKey="RandevuID", IsForeignKey=true)]
		public tbl_Randevular tbl_Randevular
		{
			get
			{
				return this._tbl_Randevular.Entity;
			}
			set
			{
				tbl_Randevular previousValue = this._tbl_Randevular.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Randevular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Randevular.Entity = null;
						previousValue.tbl_MuayeneBilgileris.Remove(this);
					}
					this._tbl_Randevular.Entity = value;
					if ((value != null))
					{
						value.tbl_MuayeneBilgileris.Add(this);
						this._RandevuID = value.RandevuID;
					}
					else
					{
						this._RandevuID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Randevular");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri", Storage="_tbl_Hastalar", ThisKey="HastaID", OtherKey="HastaID", IsForeignKey=true)]
		public tbl_Hastalar tbl_Hastalar
		{
			get
			{
				return this._tbl_Hastalar.Entity;
			}
			set
			{
				tbl_Hastalar previousValue = this._tbl_Hastalar.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hastalar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hastalar.Entity = null;
						previousValue.tbl_MuayeneBilgileris.Remove(this);
					}
					this._tbl_Hastalar.Entity = value;
					if ((value != null))
					{
						value.tbl_MuayeneBilgileris.Add(this);
						this._HastaID = value.HastaID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hastalar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri1", Storage="_tbl_Hastalar1", ThisKey="HastaID", OtherKey="HastaID", IsForeignKey=true)]
		public tbl_Hastalar tbl_Hastalar1
		{
			get
			{
				return this._tbl_Hastalar1.Entity;
			}
			set
			{
				tbl_Hastalar previousValue = this._tbl_Hastalar1.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hastalar1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hastalar1.Entity = null;
						previousValue.tbl_MuayeneBilgileris1.Remove(this);
					}
					this._tbl_Hastalar1.Entity = value;
					if ((value != null))
					{
						value.tbl_MuayeneBilgileris1.Add(this);
						this._HastaID = value.HastaID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hastalar1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri2", Storage="_tbl_Hastalar2", ThisKey="HastaID", OtherKey="HastaID", IsForeignKey=true)]
		public tbl_Hastalar tbl_Hastalar2
		{
			get
			{
				return this._tbl_Hastalar2.Entity;
			}
			set
			{
				tbl_Hastalar previousValue = this._tbl_Hastalar2.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hastalar2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hastalar2.Entity = null;
						previousValue.tbl_MuayeneBilgileris2.Remove(this);
					}
					this._tbl_Hastalar2.Entity = value;
					if ((value != null))
					{
						value.tbl_MuayeneBilgileris2.Add(this);
						this._HastaID = value.HastaID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hastalar2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri3", Storage="_tbl_Hastalar3", ThisKey="HastaID", OtherKey="HastaID", IsForeignKey=true)]
		public tbl_Hastalar tbl_Hastalar3
		{
			get
			{
				return this._tbl_Hastalar3.Entity;
			}
			set
			{
				tbl_Hastalar previousValue = this._tbl_Hastalar3.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hastalar3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hastalar3.Entity = null;
						previousValue.tbl_MuayeneBilgileris3.Remove(this);
					}
					this._tbl_Hastalar3.Entity = value;
					if ((value != null))
					{
						value.tbl_MuayeneBilgileris3.Add(this);
						this._HastaID = value.HastaID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hastalar3");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri4", Storage="_tbl_Hastalar4", ThisKey="HastaID", OtherKey="HastaID", IsForeignKey=true)]
		public tbl_Hastalar tbl_Hastalar4
		{
			get
			{
				return this._tbl_Hastalar4.Entity;
			}
			set
			{
				tbl_Hastalar previousValue = this._tbl_Hastalar4.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hastalar4.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hastalar4.Entity = null;
						previousValue.tbl_MuayeneBilgileris4.Remove(this);
					}
					this._tbl_Hastalar4.Entity = value;
					if ((value != null))
					{
						value.tbl_MuayeneBilgileris4.Add(this);
						this._HastaID = value.HastaID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hastalar4");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri5", Storage="_tbl_Hastalar5", ThisKey="HastaID", OtherKey="HastaID", IsForeignKey=true)]
		public tbl_Hastalar tbl_Hastalar5
		{
			get
			{
				return this._tbl_Hastalar5.Entity;
			}
			set
			{
				tbl_Hastalar previousValue = this._tbl_Hastalar5.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hastalar5.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hastalar5.Entity = null;
						previousValue.tbl_MuayeneBilgileris5.Remove(this);
					}
					this._tbl_Hastalar5.Entity = value;
					if ((value != null))
					{
						value.tbl_MuayeneBilgileris5.Add(this);
						this._HastaID = value.HastaID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hastalar5");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Recetelers(tbl_Receteler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_MuayeneBilgileri = this;
		}
		
		private void detach_tbl_Recetelers(tbl_Receteler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_MuayeneBilgileri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Hastalar")]
	public partial class tbl_Hastalar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HastaID;
		
		private string _HastaTC;
		
		private string _HastaSifre;
		
		private string _HastaAd;
		
		private string _HastaSoyad;
		
		private string _HastaCinsiyet;
		
		private System.DateTime _HastaDogumTarihi;
		
		private string _HastaTelefon;
		
		private string _HastaMail;
		
		private string _HastaAdres;
		
		private string _HastaHesKodu;
		
		private EntitySet<tbl_FaturaBilgileri> _tbl_FaturaBilgileris;
		
		private EntitySet<tbl_HastaGecmisi> _tbl_HastaGecmisis;
		
		private EntitySet<tbl_Randevular> _tbl_Randevulars;
		
		private EntitySet<tbl_MuayeneBilgileri> _tbl_MuayeneBilgileris;
		
		private EntitySet<tbl_MuayeneBilgileri> _tbl_MuayeneBilgileris1;
		
		private EntitySet<tbl_MuayeneBilgileri> _tbl_MuayeneBilgileris2;
		
		private EntitySet<tbl_MuayeneBilgileri> _tbl_MuayeneBilgileris3;
		
		private EntitySet<tbl_MuayeneBilgileri> _tbl_MuayeneBilgileris4;
		
		private EntitySet<tbl_MuayeneBilgileri> _tbl_MuayeneBilgileris5;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHastaIDChanging(int value);
    partial void OnHastaIDChanged();
    partial void OnHastaTCChanging(string value);
    partial void OnHastaTCChanged();
    partial void OnHastaSifreChanging(string value);
    partial void OnHastaSifreChanged();
    partial void OnHastaAdChanging(string value);
    partial void OnHastaAdChanged();
    partial void OnHastaSoyadChanging(string value);
    partial void OnHastaSoyadChanged();
    partial void OnHastaCinsiyetChanging(string value);
    partial void OnHastaCinsiyetChanged();
    partial void OnHastaDogumTarihiChanging(System.DateTime value);
    partial void OnHastaDogumTarihiChanged();
    partial void OnHastaTelefonChanging(string value);
    partial void OnHastaTelefonChanged();
    partial void OnHastaMailChanging(string value);
    partial void OnHastaMailChanged();
    partial void OnHastaAdresChanging(string value);
    partial void OnHastaAdresChanged();
    partial void OnHastaHesKoduChanging(string value);
    partial void OnHastaHesKoduChanged();
    #endregion
		
		public tbl_Hastalar()
		{
			this._tbl_FaturaBilgileris = new EntitySet<tbl_FaturaBilgileri>(new Action<tbl_FaturaBilgileri>(this.attach_tbl_FaturaBilgileris), new Action<tbl_FaturaBilgileri>(this.detach_tbl_FaturaBilgileris));
			this._tbl_HastaGecmisis = new EntitySet<tbl_HastaGecmisi>(new Action<tbl_HastaGecmisi>(this.attach_tbl_HastaGecmisis), new Action<tbl_HastaGecmisi>(this.detach_tbl_HastaGecmisis));
			this._tbl_Randevulars = new EntitySet<tbl_Randevular>(new Action<tbl_Randevular>(this.attach_tbl_Randevulars), new Action<tbl_Randevular>(this.detach_tbl_Randevulars));
			this._tbl_MuayeneBilgileris = new EntitySet<tbl_MuayeneBilgileri>(new Action<tbl_MuayeneBilgileri>(this.attach_tbl_MuayeneBilgileris), new Action<tbl_MuayeneBilgileri>(this.detach_tbl_MuayeneBilgileris));
			this._tbl_MuayeneBilgileris1 = new EntitySet<tbl_MuayeneBilgileri>(new Action<tbl_MuayeneBilgileri>(this.attach_tbl_MuayeneBilgileris1), new Action<tbl_MuayeneBilgileri>(this.detach_tbl_MuayeneBilgileris1));
			this._tbl_MuayeneBilgileris2 = new EntitySet<tbl_MuayeneBilgileri>(new Action<tbl_MuayeneBilgileri>(this.attach_tbl_MuayeneBilgileris2), new Action<tbl_MuayeneBilgileri>(this.detach_tbl_MuayeneBilgileris2));
			this._tbl_MuayeneBilgileris3 = new EntitySet<tbl_MuayeneBilgileri>(new Action<tbl_MuayeneBilgileri>(this.attach_tbl_MuayeneBilgileris3), new Action<tbl_MuayeneBilgileri>(this.detach_tbl_MuayeneBilgileris3));
			this._tbl_MuayeneBilgileris4 = new EntitySet<tbl_MuayeneBilgileri>(new Action<tbl_MuayeneBilgileri>(this.attach_tbl_MuayeneBilgileris4), new Action<tbl_MuayeneBilgileri>(this.detach_tbl_MuayeneBilgileris4));
			this._tbl_MuayeneBilgileris5 = new EntitySet<tbl_MuayeneBilgileri>(new Action<tbl_MuayeneBilgileri>(this.attach_tbl_MuayeneBilgileris5), new Action<tbl_MuayeneBilgileri>(this.detach_tbl_MuayeneBilgileris5));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaTC", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string HastaTC
		{
			get
			{
				return this._HastaTC;
			}
			set
			{
				if ((this._HastaTC != value))
				{
					this.OnHastaTCChanging(value);
					this.SendPropertyChanging();
					this._HastaTC = value;
					this.SendPropertyChanged("HastaTC");
					this.OnHastaTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaSifre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HastaSifre
		{
			get
			{
				return this._HastaSifre;
			}
			set
			{
				if ((this._HastaSifre != value))
				{
					this.OnHastaSifreChanging(value);
					this.SendPropertyChanging();
					this._HastaSifre = value;
					this.SendPropertyChanged("HastaSifre");
					this.OnHastaSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaAd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HastaAd
		{
			get
			{
				return this._HastaAd;
			}
			set
			{
				if ((this._HastaAd != value))
				{
					this.OnHastaAdChanging(value);
					this.SendPropertyChanging();
					this._HastaAd = value;
					this.SendPropertyChanged("HastaAd");
					this.OnHastaAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaSoyad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HastaSoyad
		{
			get
			{
				return this._HastaSoyad;
			}
			set
			{
				if ((this._HastaSoyad != value))
				{
					this.OnHastaSoyadChanging(value);
					this.SendPropertyChanging();
					this._HastaSoyad = value;
					this.SendPropertyChanged("HastaSoyad");
					this.OnHastaSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaCinsiyet", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string HastaCinsiyet
		{
			get
			{
				return this._HastaCinsiyet;
			}
			set
			{
				if ((this._HastaCinsiyet != value))
				{
					this.OnHastaCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._HastaCinsiyet = value;
					this.SendPropertyChanged("HastaCinsiyet");
					this.OnHastaCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaDogumTarihi", DbType="Date NOT NULL")]
		public System.DateTime HastaDogumTarihi
		{
			get
			{
				return this._HastaDogumTarihi;
			}
			set
			{
				if ((this._HastaDogumTarihi != value))
				{
					this.OnHastaDogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._HastaDogumTarihi = value;
					this.SendPropertyChanged("HastaDogumTarihi");
					this.OnHastaDogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaTelefon", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string HastaTelefon
		{
			get
			{
				return this._HastaTelefon;
			}
			set
			{
				if ((this._HastaTelefon != value))
				{
					this.OnHastaTelefonChanging(value);
					this.SendPropertyChanging();
					this._HastaTelefon = value;
					this.SendPropertyChanged("HastaTelefon");
					this.OnHastaTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaMail", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string HastaMail
		{
			get
			{
				return this._HastaMail;
			}
			set
			{
				if ((this._HastaMail != value))
				{
					this.OnHastaMailChanging(value);
					this.SendPropertyChanging();
					this._HastaMail = value;
					this.SendPropertyChanged("HastaMail");
					this.OnHastaMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaAdres", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string HastaAdres
		{
			get
			{
				return this._HastaAdres;
			}
			set
			{
				if ((this._HastaAdres != value))
				{
					this.OnHastaAdresChanging(value);
					this.SendPropertyChanging();
					this._HastaAdres = value;
					this.SendPropertyChanged("HastaAdres");
					this.OnHastaAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaHesKodu", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HastaHesKodu
		{
			get
			{
				return this._HastaHesKodu;
			}
			set
			{
				if ((this._HastaHesKodu != value))
				{
					this.OnHastaHesKoduChanging(value);
					this.SendPropertyChanging();
					this._HastaHesKodu = value;
					this.SendPropertyChanged("HastaHesKodu");
					this.OnHastaHesKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_FaturaBilgileri", Storage="_tbl_FaturaBilgileris", ThisKey="HastaID", OtherKey="HastaID")]
		public EntitySet<tbl_FaturaBilgileri> tbl_FaturaBilgileris
		{
			get
			{
				return this._tbl_FaturaBilgileris;
			}
			set
			{
				this._tbl_FaturaBilgileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_HastaGecmisi", Storage="_tbl_HastaGecmisis", ThisKey="HastaID", OtherKey="HastaID")]
		public EntitySet<tbl_HastaGecmisi> tbl_HastaGecmisis
		{
			get
			{
				return this._tbl_HastaGecmisis;
			}
			set
			{
				this._tbl_HastaGecmisis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_Randevular", Storage="_tbl_Randevulars", ThisKey="HastaID", OtherKey="HastaID")]
		public EntitySet<tbl_Randevular> tbl_Randevulars
		{
			get
			{
				return this._tbl_Randevulars;
			}
			set
			{
				this._tbl_Randevulars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri", Storage="_tbl_MuayeneBilgileris", ThisKey="HastaID", OtherKey="HastaID")]
		public EntitySet<tbl_MuayeneBilgileri> tbl_MuayeneBilgileris
		{
			get
			{
				return this._tbl_MuayeneBilgileris;
			}
			set
			{
				this._tbl_MuayeneBilgileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri1", Storage="_tbl_MuayeneBilgileris1", ThisKey="HastaID", OtherKey="HastaID")]
		public EntitySet<tbl_MuayeneBilgileri> tbl_MuayeneBilgileris1
		{
			get
			{
				return this._tbl_MuayeneBilgileris1;
			}
			set
			{
				this._tbl_MuayeneBilgileris1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri2", Storage="_tbl_MuayeneBilgileris2", ThisKey="HastaID", OtherKey="HastaID")]
		public EntitySet<tbl_MuayeneBilgileri> tbl_MuayeneBilgileris2
		{
			get
			{
				return this._tbl_MuayeneBilgileris2;
			}
			set
			{
				this._tbl_MuayeneBilgileris2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri3", Storage="_tbl_MuayeneBilgileris3", ThisKey="HastaID", OtherKey="HastaID")]
		public EntitySet<tbl_MuayeneBilgileri> tbl_MuayeneBilgileris3
		{
			get
			{
				return this._tbl_MuayeneBilgileris3;
			}
			set
			{
				this._tbl_MuayeneBilgileris3.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri4", Storage="_tbl_MuayeneBilgileris4", ThisKey="HastaID", OtherKey="HastaID")]
		public EntitySet<tbl_MuayeneBilgileri> tbl_MuayeneBilgileris4
		{
			get
			{
				return this._tbl_MuayeneBilgileris4;
			}
			set
			{
				this._tbl_MuayeneBilgileris4.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hastalar_tbl_MuayeneBilgileri5", Storage="_tbl_MuayeneBilgileris5", ThisKey="HastaID", OtherKey="HastaID")]
		public EntitySet<tbl_MuayeneBilgileri> tbl_MuayeneBilgileris5
		{
			get
			{
				return this._tbl_MuayeneBilgileris5;
			}
			set
			{
				this._tbl_MuayeneBilgileris5.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_FaturaBilgileris(tbl_FaturaBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar = this;
		}
		
		private void detach_tbl_FaturaBilgileris(tbl_FaturaBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar = null;
		}
		
		private void attach_tbl_HastaGecmisis(tbl_HastaGecmisi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar = this;
		}
		
		private void detach_tbl_HastaGecmisis(tbl_HastaGecmisi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar = null;
		}
		
		private void attach_tbl_Randevulars(tbl_Randevular entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar = this;
		}
		
		private void detach_tbl_Randevulars(tbl_Randevular entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar = null;
		}
		
		private void attach_tbl_MuayeneBilgileris(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar = this;
		}
		
		private void detach_tbl_MuayeneBilgileris(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar = null;
		}
		
		private void attach_tbl_MuayeneBilgileris1(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar1 = this;
		}
		
		private void detach_tbl_MuayeneBilgileris1(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar1 = null;
		}
		
		private void attach_tbl_MuayeneBilgileris2(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar2 = this;
		}
		
		private void detach_tbl_MuayeneBilgileris2(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar2 = null;
		}
		
		private void attach_tbl_MuayeneBilgileris3(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar3 = this;
		}
		
		private void detach_tbl_MuayeneBilgileris3(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar3 = null;
		}
		
		private void attach_tbl_MuayeneBilgileris4(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar4 = this;
		}
		
		private void detach_tbl_MuayeneBilgileris4(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar4 = null;
		}
		
		private void attach_tbl_MuayeneBilgileris5(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar5 = this;
		}
		
		private void detach_tbl_MuayeneBilgileris5(tbl_MuayeneBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hastalar5 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Doktorlar")]
	public partial class tbl_Doktorlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DoktorID;
		
		private string _DoktorTC;
		
		private string _DoktorSifre;
		
		private string _DoktorAd;
		
		private string _DoktorSoyad;
		
		private string _DoktorCinsiyet;
		
		private System.DateTime _DoktorDoğumTarihi;
		
		private string _DoktorTelefon;
		
		private string _DoktorMail;
		
		private string _DoktorAdres;
		
		private string _DoktorUzmanlik;
		
		private string _DoktorPolikinik;
		
		private string _DoktorHesKodu;
		
		private System.Nullable<int> _BolumID;
		
		private EntitySet<tbl_Randevular> _tbl_Randevulars;
		
		private EntityRef<tbl_Bolum> _tbl_Bolum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDoktorIDChanging(int value);
    partial void OnDoktorIDChanged();
    partial void OnDoktorTCChanging(string value);
    partial void OnDoktorTCChanged();
    partial void OnDoktorSifreChanging(string value);
    partial void OnDoktorSifreChanged();
    partial void OnDoktorAdChanging(string value);
    partial void OnDoktorAdChanged();
    partial void OnDoktorSoyadChanging(string value);
    partial void OnDoktorSoyadChanged();
    partial void OnDoktorCinsiyetChanging(string value);
    partial void OnDoktorCinsiyetChanged();
    partial void OnDoktorDoğumTarihiChanging(System.DateTime value);
    partial void OnDoktorDoğumTarihiChanged();
    partial void OnDoktorTelefonChanging(string value);
    partial void OnDoktorTelefonChanged();
    partial void OnDoktorMailChanging(string value);
    partial void OnDoktorMailChanged();
    partial void OnDoktorAdresChanging(string value);
    partial void OnDoktorAdresChanged();
    partial void OnDoktorUzmanlikChanging(string value);
    partial void OnDoktorUzmanlikChanged();
    partial void OnDoktorPolikinikChanging(string value);
    partial void OnDoktorPolikinikChanged();
    partial void OnDoktorHesKoduChanging(string value);
    partial void OnDoktorHesKoduChanged();
    partial void OnBolumIDChanging(System.Nullable<int> value);
    partial void OnBolumIDChanged();
    #endregion
		
		public tbl_Doktorlar()
		{
			this._tbl_Randevulars = new EntitySet<tbl_Randevular>(new Action<tbl_Randevular>(this.attach_tbl_Randevulars), new Action<tbl_Randevular>(this.detach_tbl_Randevulars));
			this._tbl_Bolum = default(EntityRef<tbl_Bolum>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DoktorID
		{
			get
			{
				return this._DoktorID;
			}
			set
			{
				if ((this._DoktorID != value))
				{
					this.OnDoktorIDChanging(value);
					this.SendPropertyChanging();
					this._DoktorID = value;
					this.SendPropertyChanged("DoktorID");
					this.OnDoktorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorTC", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string DoktorTC
		{
			get
			{
				return this._DoktorTC;
			}
			set
			{
				if ((this._DoktorTC != value))
				{
					this.OnDoktorTCChanging(value);
					this.SendPropertyChanging();
					this._DoktorTC = value;
					this.SendPropertyChanged("DoktorTC");
					this.OnDoktorTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorSifre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DoktorSifre
		{
			get
			{
				return this._DoktorSifre;
			}
			set
			{
				if ((this._DoktorSifre != value))
				{
					this.OnDoktorSifreChanging(value);
					this.SendPropertyChanging();
					this._DoktorSifre = value;
					this.SendPropertyChanged("DoktorSifre");
					this.OnDoktorSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorAd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DoktorAd
		{
			get
			{
				return this._DoktorAd;
			}
			set
			{
				if ((this._DoktorAd != value))
				{
					this.OnDoktorAdChanging(value);
					this.SendPropertyChanging();
					this._DoktorAd = value;
					this.SendPropertyChanged("DoktorAd");
					this.OnDoktorAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorSoyad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DoktorSoyad
		{
			get
			{
				return this._DoktorSoyad;
			}
			set
			{
				if ((this._DoktorSoyad != value))
				{
					this.OnDoktorSoyadChanging(value);
					this.SendPropertyChanging();
					this._DoktorSoyad = value;
					this.SendPropertyChanged("DoktorSoyad");
					this.OnDoktorSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorCinsiyet", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DoktorCinsiyet
		{
			get
			{
				return this._DoktorCinsiyet;
			}
			set
			{
				if ((this._DoktorCinsiyet != value))
				{
					this.OnDoktorCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._DoktorCinsiyet = value;
					this.SendPropertyChanged("DoktorCinsiyet");
					this.OnDoktorCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorDoğumTarihi", DbType="Date NOT NULL")]
		public System.DateTime DoktorDoğumTarihi
		{
			get
			{
				return this._DoktorDoğumTarihi;
			}
			set
			{
				if ((this._DoktorDoğumTarihi != value))
				{
					this.OnDoktorDoğumTarihiChanging(value);
					this.SendPropertyChanging();
					this._DoktorDoğumTarihi = value;
					this.SendPropertyChanged("DoktorDoğumTarihi");
					this.OnDoktorDoğumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorTelefon", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string DoktorTelefon
		{
			get
			{
				return this._DoktorTelefon;
			}
			set
			{
				if ((this._DoktorTelefon != value))
				{
					this.OnDoktorTelefonChanging(value);
					this.SendPropertyChanging();
					this._DoktorTelefon = value;
					this.SendPropertyChanged("DoktorTelefon");
					this.OnDoktorTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorMail", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DoktorMail
		{
			get
			{
				return this._DoktorMail;
			}
			set
			{
				if ((this._DoktorMail != value))
				{
					this.OnDoktorMailChanging(value);
					this.SendPropertyChanging();
					this._DoktorMail = value;
					this.SendPropertyChanged("DoktorMail");
					this.OnDoktorMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorAdres", DbType="VarChar(255)")]
		public string DoktorAdres
		{
			get
			{
				return this._DoktorAdres;
			}
			set
			{
				if ((this._DoktorAdres != value))
				{
					this.OnDoktorAdresChanging(value);
					this.SendPropertyChanging();
					this._DoktorAdres = value;
					this.SendPropertyChanged("DoktorAdres");
					this.OnDoktorAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorUzmanlik", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DoktorUzmanlik
		{
			get
			{
				return this._DoktorUzmanlik;
			}
			set
			{
				if ((this._DoktorUzmanlik != value))
				{
					this.OnDoktorUzmanlikChanging(value);
					this.SendPropertyChanging();
					this._DoktorUzmanlik = value;
					this.SendPropertyChanged("DoktorUzmanlik");
					this.OnDoktorUzmanlikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorPolikinik", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DoktorPolikinik
		{
			get
			{
				return this._DoktorPolikinik;
			}
			set
			{
				if ((this._DoktorPolikinik != value))
				{
					this.OnDoktorPolikinikChanging(value);
					this.SendPropertyChanging();
					this._DoktorPolikinik = value;
					this.SendPropertyChanged("DoktorPolikinik");
					this.OnDoktorPolikinikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoktorHesKodu", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string DoktorHesKodu
		{
			get
			{
				return this._DoktorHesKodu;
			}
			set
			{
				if ((this._DoktorHesKodu != value))
				{
					this.OnDoktorHesKoduChanging(value);
					this.SendPropertyChanging();
					this._DoktorHesKodu = value;
					this.SendPropertyChanged("DoktorHesKodu");
					this.OnDoktorHesKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumID", DbType="Int")]
		public System.Nullable<int> BolumID
		{
			get
			{
				return this._BolumID;
			}
			set
			{
				if ((this._BolumID != value))
				{
					if (this._tbl_Bolum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBolumIDChanging(value);
					this.SendPropertyChanging();
					this._BolumID = value;
					this.SendPropertyChanged("BolumID");
					this.OnBolumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Doktorlar_tbl_Randevular", Storage="_tbl_Randevulars", ThisKey="DoktorID", OtherKey="DoktorID")]
		public EntitySet<tbl_Randevular> tbl_Randevulars
		{
			get
			{
				return this._tbl_Randevulars;
			}
			set
			{
				this._tbl_Randevulars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Bolum_tbl_Doktorlar", Storage="_tbl_Bolum", ThisKey="BolumID", OtherKey="BolumID", IsForeignKey=true)]
		public tbl_Bolum tbl_Bolum
		{
			get
			{
				return this._tbl_Bolum.Entity;
			}
			set
			{
				tbl_Bolum previousValue = this._tbl_Bolum.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Bolum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Bolum.Entity = null;
						previousValue.tbl_Doktorlars.Remove(this);
					}
					this._tbl_Bolum.Entity = value;
					if ((value != null))
					{
						value.tbl_Doktorlars.Add(this);
						this._BolumID = value.BolumID;
					}
					else
					{
						this._BolumID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Bolum");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Randevulars(tbl_Randevular entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Doktorlar = this;
		}
		
		private void detach_tbl_Randevulars(tbl_Randevular entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Doktorlar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Yonetici")]
	public partial class tbl_Yonetici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YoneticiID;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _TC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYoneticiIDChanging(int value);
    partial void OnYoneticiIDChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnTCChanging(string value);
    partial void OnTCChanged();
    #endregion
		
		public tbl_Yonetici()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int YoneticiID
		{
			get
			{
				return this._YoneticiID;
			}
			set
			{
				if ((this._YoneticiID != value))
				{
					this.OnYoneticiIDChanging(value);
					this.SendPropertyChanging();
					this._YoneticiID = value;
					this.SendPropertyChanged("YoneticiID");
					this.OnYoneticiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this.OnKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciAdi = value;
					this.SendPropertyChanged("KullaniciAdi");
					this.OnKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TC", DbType="NVarChar(11)")]
		public string TC
		{
			get
			{
				return this._TC;
			}
			set
			{
				if ((this._TC != value))
				{
					this.OnTCChanging(value);
					this.SendPropertyChanging();
					this._TC = value;
					this.SendPropertyChanged("TC");
					this.OnTCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Duyuru")]
	public partial class tbl_Duyuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DuyuruID;
		
		private string _Baslik;
		
		private string _Icerik;
		
		private System.DateTime _Tarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDuyuruIDChanging(int value);
    partial void OnDuyuruIDChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnIcerikChanging(string value);
    partial void OnIcerikChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    #endregion
		
		public tbl_Duyuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuyuruID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DuyuruID
		{
			get
			{
				return this._DuyuruID;
			}
			set
			{
				if ((this._DuyuruID != value))
				{
					this.OnDuyuruIDChanging(value);
					this.SendPropertyChanging();
					this._DuyuruID = value;
					this.SendPropertyChanged("DuyuruID");
					this.OnDuyuruIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Baslik
		{
			get
			{
				return this._Baslik;
			}
			set
			{
				if ((this._Baslik != value))
				{
					this.OnBaslikChanging(value);
					this.SendPropertyChanging();
					this._Baslik = value;
					this.SendPropertyChanged("Baslik");
					this.OnBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icerik", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Icerik
		{
			get
			{
				return this._Icerik;
			}
			set
			{
				if ((this._Icerik != value))
				{
					this.OnIcerikChanging(value);
					this.SendPropertyChanging();
					this._Icerik = value;
					this.SendPropertyChanged("Icerik");
					this.OnIcerikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
